arch: resnet50

total_batch_size: 8192
physical_batch_size: 32
bn_batch_size: 32

opt: SGD
lr: 0.5
beta1: 0
nesterov: 0
epochs: 150

wd: 0.0001
no_wd_on_bias: 1
no_wd_on_normalizer: 1

lrdecay_sche:
  - 50
  - 100
warmup: 1
warmup_epochs: 5